### ISSUE TITLE
Back button navigation system improvements

### ISSUE THREAD

**Issue by JordanPlayz158** [TekExplorer/featherdactyl.com#11]
I notice that the profile selector is a bit slower on back functionality so either make that as fast as back button for everything else or ensure that the back animation or whatever is going on is done before allowing another back button press as if you do 2 quickly when trying to go back, it does some weird bugs such as, if you hit the back button twice, it will go one screen back but go back to the profile selector, or any other screen, it will go back to the credential screen when you press the back button this time. 

Also make it so there is a prompt when trying to back out to credential screen, in my opinion, have a logout prompt to the user. As I don't think many people will have the whole api key handy the whole time and will require people to delete and remake the api keys a lot otherwise.

And with the profile selector personally, I don't think it makes sense for that screen to have the back screen functionality, or only have it go once in a row, as in, if you go to profile manager, select profile and do that again, it will cause 4 back buttons to get to the screen before those 2 actions, so it should only require 2 back buttons, maybe only if it is the same profile over and over again and not if it's 2 different ones, I'm sorry if this is unclear.

**Comment by TekExplorer** [comment]
When you put a url and back out, backing out more doesn't work. This is now fixed.

Backing out is fine on the profile screen, as you'll just go to the route if your current profile works, or it wont let you unless you log in.

I have added a confirmation dialog to the profile manager button

I'm going to need a screen recording of the first thing, and I don't really understand the second

**Comment by TekExplorer** [comment]
Login flow now replaces itself when routing, so backing out from login or dashboard will go straight to profiles, if that was the previous route

**Comment by JordanPlayz158** [comment]
Well, I found an easy way to break the app, relating to back button navigation, if you just spam the back button, you get a blank screen

**Comment by TekExplorer** [comment]
I think I see. it looks like it manages to overlap itself somehow, duplicating a non-duplicatable key

**Comment by progremmerpro2021** [comment]
pl
