### ISSUE TITLE
[Bug]  File actions unresponsive

### ISSUE THREAD

**Issue by devnote-dev** [TekExplorer/featherdactyl.com#16]
## Build
version: 0.0.7
System: Windows 11

## Details
All of the file actions in the dropdown selection (excluding unimplemented actions) do not work. When clicking them and providing the necessary input if applicable, the modal is stuck on the screen, showing an infinite loading icon. When going out of the file manager then back into it, none of the actions have been processed. Specifically with the "Move" file action, instead of showing any kind of modal, the screen goes white (see the last screenshot).

<img width="240" alt="image" src="https://user-images.githubusercontent.com/69095599/171508632-5b5fc571-f6f0-4700-832e-b8a1780d074d.png">
<img width="440" alt="image" src="https://user-images.githubusercontent.com/69095599/171508750-731387cc-1a36-4c70-b1ae-c1f5410af439.png">
<img width="441" alt="image" src="https://user-images.githubusercontent.com/69095599/171508824-a9bf1daa-a5ea-4826-b6ed-245432a013f0.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/69095599/171509081-d53923a1-6d05-468c-adbe-6836936e1a13.png">

**Comment by TekExplorer** [comment]
What is your panel version?

**Comment by devnote-dev** [comment]
1.7.0

**Comment by TekExplorer** [comment]
> 1.7.0 and Wings is 1.6

that might be it tbh. my panel is updated to 1.8.1 and it works fine. in the future i might look at supporting a range of panel versions, but not right now.

update and let me know if it works :)

**Comment by devnote-dev** [comment]
Tested on 1.8.1, issues are still present. I can also reproduce on the TestFlight builds (iOS 15).

**Comment by devnote-dev** [comment]
Issues are persistent on versions 0.0.8, 0.0.9, 0.0.10 on Windows, and 0.0.11. For the delete action specifically, deleting a file shows the "delete directory" popup, and the "delete file" popup for directories.

**Comment by TekExplorer** [comment]
Should be fixed for `v0.0.12`
Please confirm.

**Comment by devnote-dev** [comment]
Fixed on Windows, I'll close this and reopen if it's still present on iOS.
