### ISSUE TITLE
 [Bug] Can't see the status of a pulling docker image

### ISSUE THREAD

**Issue by QuintenQVD0** [TekExplorer/featherdactyl.com#18]
Build
 version: 0.0.7
 System: android 11

Details
When you start a server and the docker image is not present on the machine it pulls it and shows the status on the website but on the app you don't see that status

**Comment by TekExplorer** [comment]
Good catch!
I only showed console output, not install output. easy fix.

**Comment by TekExplorer** [comment]
This should be fixed.
