### ISSUE TITLE
[Bug] "back" button unresponsive

### ISSUE THREAD

**Issue by devnote-dev** [TekExplorer/featherdactyl.com#21]
**Describe the bug**
When going to the account page, the "back" button does not work. I am still able to go to the preferences page and profiles page and go back from there, but it stays stuck on the account page.

**To Reproduce**
1. Go to the Account page
2. Press the "back" button (←)

**Expected behavior**
It should go back to the previous page.

**Screenshots**
Not really useful as they don't show much.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 0.0.13

**Smartphone (please complete the following information):**
 - Device: Untested
 - OS: Untested
 - Version: Untested

**Additional context**
N/A.

**Comment by TekExplorer** [comment]
oh, it looks like i set it to pop() instead of going back. considering things are nested, not stacked, it makes sense that failed

**Comment by devnote-dev** [comment]
Fixed in 0.0.14 👍
