### ISSUE TITLE
[Bug] Console not working on MacOS, IOS and iPadOS

### ISSUE THREAD

**Issue by Hutch79** [TekExplorer/featherdactyl.com#23]
**Describe the bug**
The console is not working in IOS, iPadOS and macOS.
Not working means that sent commands will not be sent to the server and that the console is just gray.

**To Reproduce**
Open a console and try to send a command. Then check on the Web Panel if the command was sent.
Tested with a Bungeecord and the glist command.

**Expected behavior**
It should show the console with the same font as the file editor, as well as send commands to the server.

**Screenshot**
<img src="https://user-images.githubusercontent.com/42042811/173527772-eefd7483-1473-494a-833e-f71642588e89.png" width=30% height=30%>

**Desktop (please complete the following information):**
 - Device: MacBook Air 2020 M1 
 - OS: MacOS 12.4
 - Version: 0.0.15

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max & iPad Pro 2018
 - OS: IOS 15.5 & iPadOS 15.5
 - Version: 0.0.16

**Additional context**
Before the font was not visible, it was a strange type of font, probably buggy. IOS, as well as iPadOS. (MacOS Not tested back then)
<img src="https://user-images.githubusercontent.com/42042811/173523574-e3e40c9a-7b8e-48dc-b3a2-eb0924ace299.png" width=50% height=50%>

**Comment by Hutch79** [comment]
Never mind.
The console works just fine, it was my company's Wi-Fi that has blocked some stuff.

**Comment by TekExplorer** [comment]
Remember to double check with a data connection next time 😉
