### ISSUE TITLE
[Bug] Font Problems in console - on IOS/iPadOS

### ISSUE THREAD

**Issue by Hutch79** [TekExplorer/featherdactyl.com#24]
**Describe the bug**
The font of the console is very buggy. In the filemanager it looks fine.
The Problem only exists on IOS and iPadOS, not on MacOS

**To Reproduce**
Just open the console.

**Expected behavior**
I guess it should be the same font as in the text editor, because there it looks fine.

**Screenshots**
<img src="https://user-images.githubusercontent.com/42042811/173523574-e3e40c9a-7b8e-48dc-b3a2-eb0924ace299.png" width=50% height=50%>

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max, iPad Pro 2018
 - OS: IOS 15.5, iPadOS 15.5
 - Version: 0.0.16

**Additional context**
Since at least version 0.0.6

**Comment by TekExplorer** [comment]
**_I DONT KNOW WHEN OR HOW BUT ITS FIXED_**

**Comment by Hutch79** [comment]
😂
As long as it works🤣
