### ISSUE TITLE
[Suggestion] Minimum Window Size

### ISSUE THREAD

**Issue by devnote-dev** [TekExplorer/featherdactyl.com#25]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
There should be a minimum window size when resizing the app (only applies to the desktop version). Resizing the app currently works well but can start to get cluttered and out of shape if the window size gets too small.

**Describe alternatives you've considered**
There aren't any that I found.

**Additional context**
None.

**Comment by TekExplorer** [comment]
this is now implemented.
minimum desktop window size is 400x400
