### ISSUE TITLE
[Suggestion] Auto-focus console command field. 

### ISSUE THREAD

**Issue by Nexusatko** [TekExplorer/featherdactyl.com#27]
| **Is your feature request related to a problem? Please describe.**
> When you type something in console and press enter, it'll un-focus and you have to click a field to be able to type again.

| **Describe the solution you'd like**
> It would be nice if it was made to doesn't un-focus so you can smoothly type in commands and things without being disturbed by the un-focusing text field. 

| **Describe alternatives you've considered**
> Or either make it so, that when you press enter, it'll enter the text field so you can instantly type. That would be nice for example in multi-tasking. 

| **Additional context**

> https://user-images.githubusercontent.com/59520956/174149568-c86577d2-473f-4800-a9e0-ae9b5d65d39f.mp4

**Comment by drjayy** [comment]
I agree. The possibility to write several commands in a row without unfocusing/having to reclick the command line would be a great addition.

**Comment by TekExplorer** [comment]
This was added pretty quickly and will be a part of the next release.

**Comment by TekExplorer** [comment]
Added in `v0.0.19`
