### ISSUE TITLE
[Suggestion] Add Quote Formatting for Issue Text

### ISSUE THREAD

**Issue by drjayy** [TekExplorer/featherdactyl.com#28]
**Describe the solution you'd like**

> I'd imagine the default formatting of these feature and bug requests to be Quote Formatting as seen in the screenshot below

>This would make it more convenient throughout all github issues of this repo and makes it easier to grab and read important information.

**Describe alternatives you've considered**

>An alternative would implement another formatting option such as code snippets, but I consider such options less useful than quote formatting. 

>You could also leave it as it is which will ultimately lead to a "little mess" when it comes to reading issues or feature requests

**Screenshot**
![Screenshot_20220617-144105_GitHub.jpg](https://user-images.githubusercontent.com/77808206/174300255-38bce43a-70bb-4e0b-a679-f48419c3f966.jpg)
![Screenshot_20220617-144242_GitHub.jpg](https://user-images.githubusercontent.com/77808206/174300498-36a4315d-13b4-405a-8a60-8f7b39a6d49d.jpg)

**Comment by TekExplorer** [comment]
I dont apply any formatting to these templates. honestly, i dont know why it shows as code blocks...

**Comment by drjayy** [comment]
That's fine too. Don't worry about it

**Comment by drjayy** [comment]
**I've changed this issue to quote formatting as code snippets are hard to read with large blocks of text.**

However Code Snippets would be quite useful when mentioning Version Numbers as seen in the screenshot below.

![Screenshot_20220617-144542_GitHub.jpg](https://user-images.githubusercontent.com/77808206/174301128-6c0e1478-08a9-410d-b84d-21c06dad4619.jpg)

**Comment by TekExplorer** [comment]
quote formatting seems kinda pointless, though the idea to have some things in a code block isnt a bad idea

**Comment by TekExplorer** [comment]
ive updated them. feel free to reopen if it could be improved
