### ISSUE TITLE
[Bug] Gray screen when not having a profile (first install) - Windows

### ISSUE THREAD

**Issue by WavingCatDevs** [TekExplorer/featherdactyl.com#29]
**Describe the bug**
When first installing featherdactyl on windows, the app just shows a gray screen.

**To Reproduce**
Not have a "shared_preferences.json" in the app files, when installing the app it does not create one manually. 

**Expected behavior**
It creating the "shared_preferences.json" automatically. 

**Screenshots**
![unknown](https://user-images.githubusercontent.com/69034430/174310872-d9266fad-a8e6-4ecd-b4e8-d509fe7bf2fc.png)

**App (please complete the following information):**
 - Version: 0.0.18
 - Build Number: unknown

**Desktop**
 - OS: Windows 10
 - Version: 21H2

**Comment by devnote-dev** [comment]
Same issue occurs if you delete all profiles. I had replaced the key for mine and needed to add a new profile with it, but it stays grey.

**Comment by TekExplorer** [comment]
This is due to an issue with how the url is detected. if its empty, an exception is thrown

**Comment by TekExplorer** [comment]
a fix should be coming shortly

**Comment by WavingCatDevs** [comment]
Fixed on latest version "v0.0.19"
