### ISSUE TITLE
[Bug] When putting an invalid key & panel URL it is stuck on a loading state - Windows

### ISSUE THREAD

**Issue by WavingCatDevs** [TekExplorer/featherdactyl.com#30]
**Describe the bug**
Putting a random panel URL and API key, the spinner is infinitely spinning 

**To Reproduce**
1. Go to login
2. Put a random string of letters that make a domain (EG: fkjssdjfljsdflsjdfkls.com)
3. Put a random string of letters for API key (EG: klkdasaks)
4. Click login

**Expected behavior**
Return back an error of something like "Invalid key / URL)

**Screenshots**
![Capture](https://user-images.githubusercontent.com/69034430/174313681-84cf908b-0fb6-4b0a-894b-15af8f3bd5a3.PNG)

**App (please complete the following information):**
 - Version: 0.0.18
 - Build Number: unknown

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 21H2

**Comment by TekExplorer** [comment]
this may be a duplicate of #29 
once v0.0.19 is out check this again.

**Comment by WavingCatDevs** [comment]
> this may be a duplicate of #29 once v0.0.19 is out check this again.

Issue still occurs on "v0.0.19"

**Comment by TekExplorer** [comment]
how long are api keys?

**Comment by TekExplorer** [comment]
i see the issue. i have it fixed locally. as its not as breaking as the bug i just published a release for, it will wait until i publish something more substantial

**Comment by WavingCatDevs** [comment]
Fixed on latest version "v0.0.20"
