### ISSUE TITLE
[Bug] Featherdactyl Stuck on Loading Screen [Android Internal Testing]

### ISSUE THREAD

**Issue by drjayy** [TekExplorer/featherdactyl.com#31]
**Describe the bug**
> Featherdactyl Android Internal Tester App is stuck on loading screen after updating to v0.0.20. The app functions normally after complete app data wipe or reinstall. (Cache clear or force stop doesn't help)

**To Reproduce**
```
1. Go to Android Google Playstore
2. Click on Update
3. Open the app
4. See error
5. Clear App Data or Reinstall
```
**Expected behavior**
> The app should function and start as normal without issues or loading freezes.

**Screenshots**
![Screenshot_20220617-232408.jpg](https://user-images.githubusercontent.com/77808206/174403853-08132dfb-7f45-4e2e-8662-f2cac7869989.jpg)

**App (please complete the following information):**
```
Version: v0.0.20
Build Number: 212
```
**Smartphone (please complete the following information):**
```
Device: Samsung Note 20
OS: Android
Version: 12
Build Number: SP1A.210812.016.N980FXXS3FVC8
```
**Additional context**
> No Context or Logs needed I believe. If I'm wrong, please say so.

**Comment by TekExplorer** [comment]
This should be fixed. Please confirm

**Comment by drjayy** [comment]
Seems to be functional for `v0.0.22` with `build number: 224` but can't confirm fully as I can't confirm if it's temporarily or permanently working
