### ISSUE TITLE
[Suggestion] Update Key Modal

### ISSUE THREAD

**Issue by devnote-dev** [TekExplorer/featherdactyl.com#33]
**Is your feature request related to a problem? Please describe.**
This is in relation to #29 and #32: if the API key for the app is deleted, the profile needs to be recreated. While this isn't a problem it can be a long process.

**Describe the solution you'd like**
If the key for an existing profile is not working (i.e. 401/403) show a popup modal with the option to update the key.

**Describe alternatives you've considered**
Recreating the profile is the only current alternative, this would be a nice feature to have though.

**Additional context**
See #32.

**Comment by TekExplorer** [comment]
this should be fixed. please confirm, and if it is not, reopen.
