### ISSUE TITLE
[Bug] AppBar doesn't update correctly/reliably on the account page

### ISSUE THREAD

**Issue by drjayy** [TekExplorer/featherdactyl.com#35]
**For reference, what is the current latest app version?**
```
Version: v0.0.22
Build: 224
```

**Is your feature request related to a problem? Please describe.**
> As of my knowledge, it isn't possible to get `back to the server list home screen` other than using `back buttons` when being inside the manage account window as seen below.

**Describe the solution you'd like**
> You could simply make the `Dashboard Text` or `Pterodactyl Icon clickable` so you can easily get back to the server list. 
[Simply put: A clickable server list shortcut]

**Describe alternatives you've considered**
> An alternative would be a simple back button, but it would use up more space inside the UI which isn't really perfect as an option.

**Additional context**
![Screenshot_20220621-233645.jpg](https://user-images.githubusercontent.com/77808206/174902265-ab6ce057-3a09-4272-873e-51b9314f3543.jpg)

**Comment by yesBad** [comment]
Please <3

**Comment by TekExplorer** [comment]
this is supposed to show a back button and the title is supposed to say `Account`
![image](https://user-images.githubusercontent.com/30291302/174902589-00047854-8ca7-4ecf-92c8-c4fde852c93f.png)

this is a bug

**Comment by drjayy** [comment]
> this is supposed to show a back button and the title is supposed to say `Account`
> ![image](https://user-images.githubusercontent.com/30291302/174902589-00047854-8ca7-4ecf-92c8-c4fde852c93f.png)
> 
> this is a bug

Well, I expected anything but not this, thanks for clarifying xD

**Comment by drjayy** [comment]
https://haste.oaka.xyz/adohokusum

Posting logs here aswell, visible in discord too.
