### ISSUE TITLE
[Bug] Status Indicator Type with Card Edges set to Around/Top

### ISSUE THREAD

**Issue by Liyf4TakingLs** [TekExplorer/featherdactyl.com#37]
**Description**
 After changing the "Preferences - Status Indicator Type" to "Card Edges" and the Inset to Around (or top) I noticed that the first server on the page is "fading" into the green and it doesnt look good

**To Reproduce**
```
1. Go to Preferences
2. Change the Status Indicator type to Card Edges
3. Change the Inset to Around or Top
4. Open any server page
```
**Expected behavior**
The server status should not be affected by the fade on the default page load. Only if you start scrolling down. (Simply modify the margin between the header and the server list)

**Screenshots:**
https://gyazo.com/ad0a97cf26eca5fc5529dee7bf0b7c4d

**App (please complete the following information):**
```
- Version: v0.0.22
- Build: 224
```
**Smartphone (please complete the following information):**
```
 - Device: Samsung Galaxy S20 (Includes iOS and Windows)
 - Model: SM-G980F/DS
 - OS: Android 12
```

**Comment by TekExplorer** [comment]
Is this still the case?
