### ISSUE TITLE
[Suggestion] Improvement for Theme Picker

### ISSUE THREAD

**Issue by Liyf4TakingLs** [TekExplorer/featherdactyl.com#38]
**For reference, what is the current latest app version?**
```
Version: v0.0.22
Build: 224
````

Currently the random theme option does not make sense (as stated in discord, just a gimmick). 

**Describe the solution you'd like**
A colour picker where you can choose the exact color you want. A randomize button could still be there for the funs.

**Describe alternatives you've considered**
Or even just being able to pick from limited amount of preset colors. Tho the option above provides a lot more customization.

**Additional context**
With this you could also add more configurations. Like a background specific color and etc.

**Comment by TekExplorer** [comment]
Forgot this issue was still here. closing on account of the updated theme system.
