### ISSUE TITLE
[Suggestion] (internal) File Manager Cache System

### ISSUE THREAD

**Issue by devnote-dev** [TekExplorer/featherdactyl.com#44]
**For reference, what is the current latest app version?**
```
Version: 0.0.22
Build: 224
```

**Is your feature request related to a problem? Please describe.**
Currently there is no caching system for the file manager, meaning that traversing through directories makes an API request each time, as well as for going back directories. While this isn't really an issue, there is the potential of running into performance issues in the future when the app is handling more processes or other factors.

**Describe the solution you'd like**
A system for caching files/directories, only fetching from the API if the directory is not cached. This would reduce the number of API requests being made, consequently improving performance, and give the "refresh folder" button more of a purpose.

Key things to note about implementing such a system would be file actions' effect on the cache, this would need to be monitored and updated accordingly to prevent old files/directories getting stuck in the cache. A cache interval would also be ideal depending on how this is implanted, but more detail can be provided later on.

**Describe alternatives you've considered**
There are none as this isn't really a bug, but would definitely improve on the current system.

**Additional context**
See feedback channel in the server.

**Comment by TekExplorer** [comment]
I implemented this at some point. closing.
the current implementation retains the cache for 10 minutes.
actions will eagerly alter the cache if possible (deletion will remove a file entirely) or invalidate the cache if it cant.

If there's an alteration you'd prefer, let me know (ie, different cache time)
