### ISSUE TITLE
How about new screenshots for the Playstore with a droid 13 screenshots. The old screenshots could prevent users to download the app


### ISSUE THREAD

**Issue by Nefnief-tech** [TekExplorer/featherdactyl.com#55]
**For reference, what is the current latest app version?**
```
Version: <ex: v0.0.21>
Build: <ex: 210>
```

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TekExplorer** [comment]
Feel free to send me some screenshots on discord

**Comment by Nefnief-tech** [comment]
Im sorry but i switched from pterodactyl to another panel
