### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by starstriker0** [TekExplorer/featherdactyl.com#59]
**For reference, what is the current latest app version?**
```
Version: v0.0.58
Build: n/a
```

Hi, i recently downloaded the app and set it up and noticed a feature that's needed, add an option that if the user has admin to see servers that they don't own/ not under their account. I run a home server with a friend and we have multiple people using it to run private minecraft servers and we have our own mc server network running on it, there are times where both my friend and i are at work and don't have our laptops to need to manage these servers, if something went wrong we can't manage anything on our phone browsers since their too small to read, it would be nice if you added a feature when the user has admin they can see servers that they don't own

**Comment by TekExplorer** [comment]
Already exists. It's just bugged. you can get around it by making yourselves subusers on each other's servers
