### ISSUE TITLE
Ensure all non-ready things are disabled

### ISSUE THREAD

**Issue by JordanPlayz158** [TekExplorer/featherdactyl.com#6]
Certain things are still available to be clicked on and used when they don't work like, creating api keys and editing email causes a smokescreen of white

**Comment by JordanPlayz158** [comment]
Also creating api keys, in the future, ensure that description is 4 characters at least before sending when you make the functionality and ensure it is a required field

**Comment by TekExplorer** [comment]
> Also creating api keys, in the future, ensure that description is 4 characters at least before sending when you make the functionality and ensure it is a required field

Make that its own issue.

**Comment by JordanPlayz158** [comment]
I'd argue that goes hand and hand with this issue but alright.

**Comment by JordanPlayz158** [comment]
Here it is #8.
