### ISSUE TITLE
API Key creation validation so request is only sent if pterodactyl's preconditions are met

### ISSUE THREAD

**Issue by JordanPlayz158** [TekExplorer/featherdactyl.com#8]
Creating api keys currently doesn't seem to validate input and that is an issue as api keys have certain preconditions like the description is required and it must be at least 4 characters long so, the create api key functionality should ensure the description can't be empty and that the description is 4 characters before sending the request to the panel.

**Comment by TekExplorer** [comment]
So just to be clear, the requirements are
`description: >= 4 characters`
right?

**Comment by JordanPlayz158** [comment]
Yes
